project_id = "szxxwxwityixqzzmarlq"

[functions.launcher-auth]
verify_jwt = false

[functions.launcher-register]
verify_jwt = false

[functions.launcher-check-subscription]
verify_jwt = false

[functions.launcher-download]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
